; PlatformIO Project Configuration File
;
; esp_logic - Master ESP32 (Logic & Control)
; UC1 / UC3: FreeRTOS structure, UART2 comm, load management
;
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = espidf

[env:native]
platform         = native
test_build_src   = yes
build_src_filter = -<*> +<control_logic.c> +<proto_utils.c>
